sudo: required

dist: trusty

branches:
  only:
    - master

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:expanse/expanse
  - sudo add-apt-repository -y ppa:expanse/expanse-dev
  - sudo apt-get update -qq
  - sudo apt-get install gexp -y -qq
  - yes | gexp --datadir ~/.expanse-10102 &
  - sleep 5
  - killall gexp
  - yes | gexp --datadir ~/.expanse-7 &
  - sleep 5
  - killall gexp
  - npm install -g npm

install:
  - npm install
  - npm install jshint

script:
  - npm run lint
  - travis_wait 60 istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/*.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
